services:
  avalanche:
    build:
      context: ./srcs/avalanche
      dockerfile: Dockerfile
    image: avalanche
    container_name: avalanche
    restart: unless-stopped
    networks:
      - blockchain-network
    expose:
      - "9650"
    env_file:
      - ./.env
    volumes:
      - avalanche-data:/avalanche-data

  hardhat:
    build:
      context: ./srcs/hardhat
      dockerfile: Dockerfile
    image: hardhat
    container_name: hardhat
    restart: unless-stopped
    networks:
      - blockchain-network
    depends_on:
      - avalanche

networks:
  blockchain-network:
    driver: bridge

volumes:
  avalanche-data: