services:
  avalanche:
    build:
      context: ./srcs/avalanche
      dockerfile: Dockerfile
    image: avalanche
    container_name: avalanche
    restart: unless-stopped
    networks:
      - avalanche-hardhat-network #CHANGE LATER
    expose:
      - "8080" # DO I REALLY NEED TO EXPOSE IT?
      - "8081" # THE SAME?
      - "9650"

    # WHAT CHANGES FOR PORTS?
    #expose:
    #  - "9650"
    #env_file:
    #  - ./.env
    #secrets:
    #  - primary_key

  hardhat:
    build:
      context: ./srcs/hardhat
      dockerfile: Dockerfile
    image: hardhat
    container_name: hardhat
    restart: unless-stopped
    networks:
      - avalanche-hardhat-network
    #volumes:
    #  - ./contract_address:/contract_address

networks:
  avalanche-hardhat-network:
    driver: bridge # connection between container through name CHANGE LATER