services:
  avalanche:
    build:
      context: ./avalanche
      dockerfile: Dockerfile
    image: avalanche
    container_name: avalanche
    restart: unless-stopped
    volumes:
      - avalanche-data:/app/avalanche-data
    secrets:
      - avalanche_private_key
    
secrets:
  avalanche_private_key:
    file: ./secrets/avalanche_private_key.txt

volumes:
  avalanche-data: